services:
  dy-viewer:
    image: ghcr.io/xunpanda800/douyinzaixian:latest
    container_name: dy-live-viewer
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOUYIN_COOKIE=${DOUYIN_COOKIE:-}
